### PR TITLE
Ranges for /prefetch flag added.

### PR DESCRIPTION
**Pull request by gtworek**

### CODE REVIEW

**Comment by joachimmetz** [comment]
@gtworek thx for the proposed addition, note that this is a notes section that technically is not related to the data format. I mainly put it there as a note to self to look into the `/prefetch` flag. I'll not merge this PR but I'll move the info, including your addition to https://forensicswiki.xyz/wiki/index.php?title=Prefetch. If that is fine with you.

**Comment by gtworek** [comment]
Sure, you are the host here :)

--
G.
________________________________

**Comment by joachimmetz** [comment]
Added to https://forensicswiki.xyz/wiki/index.php?title=Prefetch#.2Fprefetch_flag, closing this PR and will adjust the libscca documentation.

**Comment by joachimmetz** [comment]
@gtworek so my observations do not match yours `The /prefetch:X flag is processed only, when X stays within range 0..8.`

If I use `/prefetch:9` this will result in a different prefetch file than those in the range 0..8 

Which seems to correspond with:
```
The /prefetch:# flag is looked at by the OS when we create the process -- however, it has one (and only one) purpose.
```

**Comment by gtworek** [comment]
I have confirmed this on Win10 1903 both in practice and through code analysis. Please let me investigate it further and sorry for the mess.

--
G.
________________________________

**Comment by gtworek** [comment]
I have tested it again and it works like I expected:

[cid:image001.png@01D68E77.1D8CFDC0]

--
G.

**Comment by joachimmetz** [comment]
ack, I tested with Windows 10 2004. When you say "I have tested it again and it works like I expected:"

can you elaborate a bit? does this mean that you observed `/prefetch:0` generates the same prefetch hash/file as `/prefetch:9` ?

**Comment by gtworek** [comment]
I have tested in o 2004 a moment ago. All variants:

  *   Notepad.exe
  *   Notepad.exe /prefetch:0
  *   Notepad.exe /prefetch:9

Generate the same NOTEPAD.EXE-B28CC291.pf

--
G.

**Comment by joachimmetz** [comment]
Sry my bad, looks like there was some stale data on my test system, I confirm that I've observed the same behavior on Windows 10 2004

**Comment by gtworek** [comment]
Perfect!
Thanks for re-testing.

--
G.

**Comment by joachimmetz** [comment]
Updated https://forensicswiki.xyz/wiki/index.php?title=Prefetch#.2Fprefetch_flag

**Pull request closed without merging**
